name: Stale Manager

on:
  schedule:
  - cron: "30 1 * * *"  
  workflow_dispatch:
  
permissions:
  issues: write
  
env: 
  # The number of comments that determines action, modify this variable to adjust sensitivity
  COMMENT_THRESHOLD: 5
  MARK_STALE_AFTER_SMALL: 0
  MARK_STALE_AFTER_LARGE: 60
  CLOSE_STALE_AFTER_SMALL: 1
  CLOSE_STALE_AFTER_LARGE: 14

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        operations-per-run: 200
        stale-issue-message: >-
            {
              comments<${{ env.COMMENT_THRESHOLD }}: "This issue is stale since it's been open ${{ env.MARK_STALE_AFTER_SMALL }} days with no activity. This will be closed in ${{ env.CLOSE_STALE_AFTER_SMALL }} days unless the `Closing Soon` label is removed or a comment is added. Thank you for your contributions.",
              comments>=${{ env.COMMENT_THRESHOLD }}: "This issue is stale since it's been open ${{ env.MARK_STALE_AFTER_LARGE }} days with no activity. This will be closed in ${{ env.CLOSE_STALE_AFTER_LARGE }} days unless the `Closing Soon` label is removed or a comment is added. Thank you for your contributions."
            }                    
        stale-issue-label: "closing soon"
        debug-only: false
        # Issues with less than 5 comments will be marked as "closing soon" after 30 days of inactivity
        # Issues with or more than 5 comments will be marked as "closing soon" after 60 days of inactivity
        days-before-stale: ${{ env.MARK_STALE_AFTER_SMALL }}
        # PRs wont go stale
        days-before-pr-stale: -1
        # Issues with any of these labels are checked, excluding feature request from going stale
        any-of-issue-labels: "pending-response, !feature-request"
        ignore-updates: true

  close-stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        operations-per-run: 200                 
        close-issue-message:  >-
          {
            "comments<${{ env.COMMENT_THRESHOLD }}": "This issue was closed since it's been ${{ env.CLOSE_STALE_AFTER_SMALL }} days with no activity."
            "comments>=${{ env.COMMENT_THRESHOLD }}": "This issue was closed since it's been ${{ env.CLOSE_STALE_AFTER_LARGE }} days with no activity."
          }    
        debug-only: false
        # Issues with less than 5 comments will be closed after 7 days of inactivity
        # Issues with or more than 5 comments will be closed after 14 days of inactivity
        days-before-close: >-
          {
            "closing soon&&comments<${{ env.COMMENT_THRESHOLD }}": ${{ env.CLOSE_STALE_AFTER_SMALL }}
            "closing soon&&comments>=${{ env.COMMENT_THRESHOLD }}": ${{ env.CLOSE_STALE_AFTER_LARGE }}
          }
        # PRs wont go stale
        days-before-pr-stale: -1
        # Issues with any of these labels are checked, excluding feature request from going stale
        any-of-issue-labels: "closing soon, !feature-request"


